CREATE TABLE contract_records (
  id CHAR(36) PRIMARY KEY,
  contract_id CHAR(36) NOT NULL,
  record_type VARCHAR(40) NOT NULL,
  record_number VARCHAR(60) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'draft',
  approval_status VARCHAR(40) NOT NULL DEFAULT 'not_submitted',
  event_date DATE NULL,
  due_date DATE NULL,
  amount DECIMAL(18, 2) NULL,
  approved_amount DECIMAL(18, 2) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'MXN',
  impact_days INT NULL,
  approved_impact_days INT NULL,
  counterparty VARCHAR(180) NULL,
  basis_clause TEXT NULL,
  calculation TEXT NULL,
  percentage DECIMAL(8, 4) NULL,
  issuer VARCHAR(180) NULL,
  beneficiary VARCHAR(180) NULL,
  valid_from DATE NULL,
  valid_until DATE NULL,
  responsible_user_id CHAR(36) NULL,
  parent_record_id CHAR(36) NULL,
  related_amendment_id CHAR(36) NULL,
  metadata JSON NULL,
  created_by_id CHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_contract_record_folio (contract_id, record_type, record_number),
  INDEX idx_contract_records_type_status (contract_id, record_type, status),
  INDEX idx_contract_records_due_date (due_date),
  FOREIGN KEY (contract_id) REFERENCES contracts (id),
  FOREIGN KEY (responsible_user_id) REFERENCES users (id),
  FOREIGN KEY (parent_record_id) REFERENCES contract_records (id),
  FOREIGN KEY (related_amendment_id) REFERENCES contract_amendments (id),
  FOREIGN KEY (created_by_id) REFERENCES users (id)
);

CREATE TABLE contract_record_actions (
  id CHAR(36) PRIMARY KEY,
  record_id CHAR(36) NOT NULL,
  action VARCHAR(50) NOT NULL,
  comment TEXT NULL,
  actor_id CHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_contract_record_actions (record_id, created_at),
  FOREIGN KEY (record_id) REFERENCES contract_records (id),
  FOREIGN KEY (actor_id) REFERENCES users (id)
);
