const LABEL_MAP: Record<string, string> = {
  draft: 'Borrador',
  in_review: 'En revisión',
  pending_approval: 'Pendiente de aprobación',
  approved: 'Aprobado',
  rejected: 'Rechazado',
  published: 'Publicado',
  expired: 'Vencido',
  expiring_soon: 'Por vencer',
  active: 'Vigente',
  closed: 'Cerrado',
  renewed: 'Renovado',
  open: 'Abierto',
  in_progress: 'En proceso',
  answered: 'Respondido',
  overdue: 'Vencido',
  in_process: 'En proceso',
  stopped: 'Detenido',
  pending: 'Pendiente',
  cancelled: 'Cancelado',
  terminated: 'Terminado',
  superseded: 'Reemplazado',
  archived: 'Archivado',
  signed: 'Firmado',
  low: 'Baja',
  normal: 'Normal',
  high: 'Alta',
  urgent: 'Urgente',
  internal: 'Interno',
  confidential: 'Confidencial',
  restricted: 'Restringido',
  public: 'Público',
  global: 'Global',
  document_specific: 'Específico del documento',
  comment: 'Comentario',
  response: 'Respuesta',
  system: 'Sistema',
  email: 'Correo',
  email_received: 'Correo recibido',
  created: 'Creado',
  updated: 'Actualizado',
  uploaded: 'Subido',
  downloaded: 'Descargado',
  printed: 'Impreso',
  deleted: 'Eliminado',
  restored: 'Restaurado',
  locked: 'Bloqueado',
  unlocked: 'Desbloqueado',
  viewed: 'Visto',
  exported: 'Exportado',
  imported: 'Importado',
  assigned: 'Asignado',
  unassigned: 'Desasignado',
  completed: 'Completado',
  failed: 'Fallido',
  sent: 'Enviado',
  provider: 'Proveedor',
  self: 'Interno',
  external: 'Externo',
};

export function normalizeLabel(value?: string | null): string {
  if (!value) return 'Sin definir';
  const lower = value.toLowerCase();
  if (LABEL_MAP[lower]) return LABEL_MAP[lower];
  return value.replaceAll('_', ' ').replace(/\b\w/g, (l) => l.toUpperCase());
}
